# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crud/lease.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='crud/lease.proto',
  package='bluzelle.curium.crud',
  syntax='proto3',
  serialized_options=b'Z\'github.com/bluzelle/curium/x/crud/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63rud/lease.proto\x12\x14\x62luzelle.curium.crud\"U\n\x05Lease\x12\x0f\n\x07seconds\x18\x01 \x01(\r\x12\x0f\n\x07minutes\x18\x02 \x01(\r\x12\r\n\x05hours\x18\x03 \x01(\r\x12\x0c\n\x04\x64\x61ys\x18\x04 \x01(\r\x12\r\n\x05years\x18\x05 \x01(\rB)Z\'github.com/bluzelle/curium/x/crud/typesb\x06proto3'
)




_LEASE = _descriptor.Descriptor(
  name='Lease',
  full_name='bluzelle.curium.crud.Lease',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds', full_name='bluzelle.curium.crud.Lease.seconds', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='minutes', full_name='bluzelle.curium.crud.Lease.minutes', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hours', full_name='bluzelle.curium.crud.Lease.hours', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='days', full_name='bluzelle.curium.crud.Lease.days', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='years', full_name='bluzelle.curium.crud.Lease.years', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=127,
)

DESCRIPTOR.message_types_by_name['Lease'] = _LEASE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Lease = _reflection.GeneratedProtocolMessageType('Lease', (_message.Message,), {
  'DESCRIPTOR' : _LEASE,
  '__module__' : 'crud.lease_pb2'
  # @@protoc_insertion_point(class_scope:bluzelle.curium.crud.Lease)
  })
_sym_db.RegisterMessage(Lease)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
